### ISSUE TITLE
Instructions for how to build the plugins

### ISSUE THREAD

**Issue by ensonic** [jd-13/WE-Core#23]
The plugins have not been build for some time it seems:
```
$ ldd ~/.vst/Songbird.so | grep "not found"
	libidn.so.11 => not found
	libgcrypt.so.11 => not found
	librtmp.so.0 => not found
 $ ldd ~/.vst/Carve.so | grep "not found"
	libidn.so.11 => not found
	libgcrypt.so.11 => not found
	librtmp.so.0 => not found
```
I have:
```
/usr/lib64/libidn.so.12.6.0
/usr/lib64/libgcrypt.so.20.2.5
/usr/lib64/librtmp.so.1
```

I have cloned the git modules, but there are no Makefiles and no instructions to build them.

**Comment by jd-13** [comment]
Hi, thanks for raising this, just to clarify, are you having trouble running the plugins available on the website or with building them from source (or both)?

**Comment by ensonic** [comment]
Building them from sources, the one on the website unfortunately don't work for me since the link against quite old version of some libs and my distributions does not ship them anymore (I am on opensuse tumbleweed).

**Comment by jd-13** [comment]
I've restructured the plugin repos now so that they contain the Projucer project files, if you open them in Projucer and set the header paths as appropriate for your system it should generate the makefile and a few other files for you when saving the project.

I'll also get some updated builds on the website in the next few weeks, let me know if you have any issues.

**Comment by ensonic** [comment]
Thanks, I have to read up on how to build Projucer stuff on linux. I used lots of different build systems, but not this one so far.
